version: '3.9'
services:
  postgres:
    container_name: baulkham-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=baulkham
      - POSTGRES_PASSWORD=baulkham
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local